### ISSUE TITLE
Clarify that author blocks and copyright area should be *empty* in anonymous review

### ISSUE THREAD

**Issue by agentmorris** [sigchi/Document-Formats#66]
There is a concern that authors occasionally (not maliciously) have specific, stylized ways of filling the author blocks and copyright areas during anonymous review that in practice reveal author identity.  Copyright block and author area should gently indicate "leave blank, with no dummy content".  

This brings up the larger question of whether the template is specifically meant to reflect a blind submission process.  That's above my pay grade.

**Comment by ayman** [comment]
Personally I think this is a non-issue and if reviewers are upset about the copyright block being used (maliciously or not) then reviewers are being overly critical as it's Sheridan's job to ensure the final is pixel perfect. 

For LaTeX some more engineering on the templates could have a 'submission' mode and a 'final' mode to do this toggle.

**Comment by ayman** [comment]
We could put a dummy copyright block there with the text to say _do not edit until submission is accepted for publication_ instead of the block that is there now which details the type of licenses the ACM offers.

**Comment by jofish** [comment]
I'd be in favor of that solution. It would have the advantage that the reserved space would more closely match the final required space for the copyright block.

**Comment by jofish** [comment]
Fixed this in Word. Here's the text to put in the LaTeX templates:

Please do not modify this text block until you receive explicit instructions.
Permission to make digital or hard copies of all or part of this work for personal or classroom use is granted without fee provided that copies are not made or distributed for profit or commercial advantage and that copies bear this notice and the full citation on the first page. Copyrights for components of this work owned by others than the author(s) must be honored. Abstracting with credit is permitted. To copy otherwise, or republish, to post on servers or to redistribute to lists, requires prior specific permission and/or a fee. Request permissions from Permissions@acm.org.
CONF '22, Jan 1 - Dec 31 2022, Authorberg.
Copyright is held by the owner/author(s). Publication rights licensed to ACM. ACM 978-1-xxxx-yyyy-z/zz/zz…$zz.00.
unique doi string will go here
